config/routes.rb
Rails.application.routes.draw do
  resources :poems
  resources :groups, only: [:index, :new, :create, :show, :update]
  #resources :users, only: [:new, :show, :create, :edit, :update]
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'

  resources :users, only: [:new, :create]
  resources :comments

  root 'welcome#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # patch '/groups/:id', to: 'groups#update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :poem
  belongs_to :user 
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :poems
  has_many :group_users
  has_many :users, through: :group_users
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/poem.rb
class Poem < ApplicationRecord
  belongs_to :group
  has_many :comments

  validates :title, presence: true, length: {minimum: 5}
  validates :content, presence: true

  def self.search(search)
    group = Group.find_by(name: search)
    group ? where("group_id == ?", group.id) : all
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments
  has_many :group_users
  has_many :groups, through: :group_users
  has_many :poems, through: :groups

  validates :name, uniqueness: true

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :current_user

  def current_user
    @user = (User.find_by(id: session[:user_id]) || User.new)
  end

  def logged_in?
    current_user.id != nil
  end

  def in_group?
    current_user.groups.any?
  end

  def require_logged_in
    return redirect_to controller: 'sessions', action: 'new' unless logged_in?
  end

  def require_group
    return redirect_to controller: 'poems', action: 'index' unless in_group?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_logged_in

  def create
    # @comment = Comment.new(comment_params)
    # @comment.save
    user = current_user
    user.comments << Comment.new(comment_params)
    user.save

    redirect_to poem_path(user.comments.last.poem)


    # @poem = Poem.find(params[:poem_id])
    # @comment = @poem.comments.create(comment_params)
    # redirect_to poem_path(@poem)
  end

  def destroy
    poem = Poem.find(params[:poem_id])
    comment = poem.comments.find(params[:id])
    comment.destroy
    redirect_to poem_path(poem)
  end

  private

  def comment_params
    params.require(:comment).permit(:description, :poem_id, :user_id)
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
before_action :require_logged_in
  def index
    @groups = Group.all
    @group = Group.new
  end

  def new
    @group = Group.new
  end

  def show
    @group = Group.find_by(id: params[:id])
  end

  def create
    @group = Group.new(group_params)
    if @group.valid?
      @group.users << current_user
      @group.save
      # current_user.groups << group_params
      redirect_to groups_path
    else
      render :new
    end
  end

  def update
    @group = Group.find(params[:id])
    if !@group.users.include?(current_user)
      @group.users << current_user
      redirect_to group_path(@group)
    else
      flash[:notice] = "YOU CANT DO THAT"
    end
  end

  private

  def group_params
    params.require(:group).permit(:name)
  end

end

app/controllers/poems_controller.rb
class PoemsController < ApplicationController
  before_action :require_group, only: [:new , :create, :edit, :update]

  def index
    @poems = Poem.all
    if params[:search]
      @poems = Poem.search(params[:search])
    else
      @poems = Poem.all
    end
  end

  def show
    @poem = Poem.find_by(id: params[:id])
    @comment = Comment.new
    @user = current_user
  end

  def new
    @poem = Poem.new
    @groups = Group.all
    @usergroups = current_user.groups
  end

  def create
    @poem = Poem.new(poem_params)
    if @poem.save
      flash[:message] = "You just created a Poem!"
      redirect_to poem_path(@poem)
    else
      # render :new
      flash[:message] = "Uh Oh"
      redirect_to new_poem_path
    end
  end

  def edit
    @poem = Poem.find_by(id: params[:id])
    if @poem.group.users.include?(current_user)
      render :edit
    else
      redirect_to poem_path(@poem)
    end
  end

  def update
    @poem = Poem.find_by(id: params[:id])
    if @poem.update(poem_params)
      redirect_to poem_path(@poem)
    else
      render :edit
    end
  end

  def destroy
    poem = Poem.find_by(id: params[:id])
    poem.destroy
    redirect_to poems_path
  end

  private

  def poem_params
    params.require(:poem).permit(:title, :content, :group_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(name: params[:user][:name])
    user = user.try(:authenticate, params[:user][:password])

    return redirect_to(controller: 'sessions', action: 'new') unless user

    session[:user_id] = user.id

    @user = user

    redirect_to controller: 'welcome', action: 'home'
  end

  def destroy
    session.delete :user_id
    redirect_to '/'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    return render :new unless @user.save
    # return redirect_to controller: 'users', action: 'new' unless @user.save
    session[:user_id] = @user.id
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :require_logged_in

  def home
    # home.html.erb
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/poems_helper.rb
module PoemsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/groups/index.html.erb
<br>
<strong> CREATE NEW GROUP </strong>
<%= form_for @group do |f| %>
  <%= f.text_field :name, list: "names_autocomplete" %>
  <datalist id="names_autocomplete">
    <% Group.all.each do |group| %>
      <option value="<%= group.name %>">
    <% end %>
  </datalist>
  <%= f.submit %>
<% end %> <br>

<strong> POEM GROUPS </strong>
<% @groups.each do |group| %>
<p> <%= link_to group.name, group_path(group) %> </p>
<% end %>


<!-- <%= form_for(@group) do |f| %>
<%= f.label :name %>
<%= f.text_field :name, list: "names_autocomplete" %>
<%= f.label :info %>
<%= f.text_area :info %>
<%= f.submit %>
<% end %> -->

app/views/groups/new.html.erb
<%= form_for(@group) do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :info %>
<%= f.text_area :info %>
<%= f.submit %>
<% end %>

app/views/groups/show.html.erb
<h5> GROUP NAME </h5>
<%= @group.name %> <br>
<h5> USERS IN GROUP </h5>
<% @group.users.each do |user| %>
<p> <%= user.name %> </p>
<% end %>
<h5> POEMS WRITTEN BY THIS GROUP </h5>
<% @group.poems.each do |poem| %>
<p> <%= link_to poem.title, poem_path(poem) %> </p>
<% end %>

<h5> JOIN GROUP </h5>
<%= form_for @group do |f| %>
<%= f.submit "Join" %>
<% end %>

<h5> CREATE A POEM </h5>
<%= link_to "Create a poem!", new_poem_path %>

app/views/layouts/application.html.erb
  <!DOCTYPE html>
  <html>
  <head>
    <title>Poem Land</title>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= link_to stylesheet_link_tag :application, "https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css"%>
  </head>
  <body>
    <!-- <nav class="navbar navbar-inverse navbar-top navbar-fixed-top">
      <div class="container-fluid">
        <div class="container">
          <div class="navbar-header">
        <button>
       <a class="navbar-brand" href="/">Home Page</a>
     </button> -->

     <!-- <div id="navbar" class="navbar-collapse collapse">
             <li><%= link_to "Groups", groups_path %></li>
             <li><%= link_to "Poems", poems_path %></li>
     </div>
     <br> -->

     <nav>
  <div class="nav-wrapper">
    <a href="#" class="brand-logo right">poemland</a>
    <ul id="nav-mobile" class="left hide-on-med-and-down">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Poems", poems_path %></li>
      <li><%= link_to "Groups", groups_path %></li>
    </ul>
  </div>
</nav>

     <!-- </div>
        </div>
      </div>
    </nav> -->
    <div id="main-container" class="container">
      <%= yield %>
    </div>
  </body>
  </html>

app/views/poems/edit.html.erb
<%= form_for @poem do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<div>
<br>
<%= f.label :content %>
<%= f.text_area :content %>
</div>
<%= f.submit %>
<% end %>

app/views/poems/index.html.erb
<% if flash[:message] %>
<div class="notice"><%= flash[:message] %> </div>
<% end %>
<br>
 <%= button_to("Create a New Poem", new_poem_path, method: :get) %>
  <br>

  <%= form_tag(groups_path, :method => "get", id: "search-form") do %>
    <%= text_field_tag :search, params[:search], placeholder: "Search Poems" %>
    <%= submit_tag "Search", :name => nil %>
  <% end %>

<h1> Welcome to Poem Land </h1>
<% @poems.each do |poem| %>
 <strong> <%= link_to poem.title, poem_path(poem) %> </strong> <br>
<% end %>

app/views/poems/new.html.erb
<% if flash[:message] %>
<div class="notice"><%= flash[:message] %> </div>
<% end %>

<br>

<%= form_for @poem do |f| %>
<%= f.label :title %>
<%= f.text_field :title %>
<div>
<br>
<%= f.label :body %>
<%= f.text_area :content %>
</div>
<%= f.collection_select :group_id, @usergroups, :id, :name, { prompt: "Choose a category" }, class: "browser-default" %>

<%= f.submit %>
<% end %>

app/views/poems/show.html.erb
<% if flash[:message] %>
<div class="notice"><%= flash[:message] %> </div>
<% end %>


<h5> <p> group name - <%= @poem.group.name %> </p> </h5>


<h3> <%= @poem.title %> </h3>

<h5> <%= @poem.content %> </h5>
<br>
<%= link_to "Edit Poem", edit_poem_path(@poem) %>


<br>
<br>
     Leave a Comment
<%= form_for @comment do |f| %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= f.hidden_field :poem_id, :value => @poem.id %>
  <%= f.hidden_field :user_id, :value => @user.id %>
  <%= f.submit "Comment" %>
<% end %>

<h5> Comments </h5>
<% @poem.comments.each do |comment| %>
<p>  <%= "#{comment.user.name}: #{comment.description}" %> </p>
<% end %>

app/views/users/home.html.erb
<h1>Hi there, <%= current_user.name %></h1>.

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <p><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</p>

    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<h1> Create a New User </h1>

<%= form_for @user, controller: 'users', action: 'create' do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit "create" %>
<% end %>

app/views/welcome/home.html.erb
<p> <h1>Greetings, <%= @user.name %></h1> </p>

<%= form_tag ({controller: 'sessions', action: 'destroy', method: 'post'}) do %>
  <input type=submit value='logout'>
<% end %>

<p> <h1> Welcome to Poem-Land! </h1> </p>

<br>
<p> <%= link_to "Click here to browse all poems!", poems_path %> </p>
<p> <%= link_to "Join a group or create your own!", groups_path %> </p>